using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using EduAdvisory_Backend.DTOs.CoursePlan;
using EduAdvisory_Backend.Interfaces.Services;
using Microsoft.Extensions.Logging;

namespace EduAdvisory_Backend.Services
{
    public class CoursePlanAiService : ICoursePlanAiService
    {
        private readonly HttpClient _http;
        private readonly ILogger<CoursePlanAiService> _logger;

        public CoursePlanAiService(HttpClient http, ILogger<CoursePlanAiService> logger)
        {
            _http = http;
            _logger = logger;
        }

        public async Task<CoursePlanAiInsightsDto> RankAndExplainAsync(
            List<CoursePlanDto> plans,
            string programCode,
            int currentSemester,
            string academicStatus,
            int creditLimit,
            CancellationToken ct = default)
        {
            if (plans == null || plans.Count == 0)
            {
                return new CoursePlanAiInsightsDto
                {
                    BestPlanIndex = 0,
                    BestPlanSummary = "No plans available.",
                    PlanInsights = new()
                };
            }

            //var apiKey = Environment.GetEnvironmentVariable("OPENAI_API_KEY");
            var apiKey = Environment.GetEnvironmentVariable("OPENAI_API_KEY");
            if (string.IsNullOrWhiteSpace(apiKey))
                throw new InvalidOperationException("OPENAI_API_KEY is not set.");

            // IMPORTANT: pick a model that exists in Responses API model list (example: gpt-4o-mini)
            // (gpt-4.1-mini is not listed in the Responses API create reference you’re using)
            var model = Environment.GetEnvironmentVariable("OPENAI_MODEL");

            // Compact payload (keep it small)
            var compact = new
            {
                programCode,
                currentSemester,
                academicStatus,
                creditLimit,
                plans = plans.Select((p, idx) => new
                {
                    planIndex = idx,
                    strategy = p.Strategy,
                    semestersPlanned = p.Semesters?.Count ?? 0,
                    estimatedGraduationTerm = p.Metrics?.EstimatedGraduationTerm ?? "",

                    semesterLoads = (p.Semesters ?? new()).Select(s => new
                    {
                        s.PlannedSemester,
                        s.TermLabel,
                        s.TotalCredits,
                        retakeCount = s.Courses?.Count(c => c.IsRetake) ?? 0,
                        coursesCount = s.Courses?.Count ?? 0,
                        sampleCourses = (s.Courses ?? new()).Take(6).Select(c => c.CourseCode).ToList()
                    }).ToList()
                }).ToList()
            };

            // JSON schema the model must return
            var schema = new
            {
                type = "object",
                additionalProperties = false,
                properties = new
                {
                    bestPlanIndex = new { type = "integer", minimum = 0 },
                    bestPlanSummary = new { type = "string" },
                    planInsights = new
                    {
                        type = "array",
                        items = new
                        {
                            type = "object",
                            additionalProperties = false,
                            properties = new
                            {
                                planIndex = new { type = "integer", minimum = 0 },
                                score = new { type = "integer", minimum = 0, maximum = 100 },
                                explanation = new { type = "string" },
                                pros = new { type = "array", items = new { type = "string" } },
                                cons = new { type = "array", items = new { type = "string" } },
                                warnings = new { type = "array", items = new { type = "string" } }
                            },
                            required = new[] { "planIndex", "score", "explanation", "pros", "cons", "warnings" }
                        }
                    }
                },
                required = new[] { "bestPlanIndex", "bestPlanSummary", "planInsights" }
            };

            var systemInstructions = """
You are evaluating ALREADY-VALID course plans generated by the system.
Do NOT propose new courses or modifications.
Your job: rank the plans and explain clearly in natural language.

Consider constraints:
- prerequisites satisfied
- offering constraint: odd semesters=Fall, even=Spring (course offered only if same parity as study-guide recommended semester)
- credit limit: PROBATION=16 else 18
- retake failed courses early
- follow study guide order as much as possible

Return STRICT JSON that matches the given schema.
""";

            var userInput = $"""
Rank these {plans.Count} plans from best to worst.
For each plan provide:
- score (0-100)
- explanation (2-4 sentences)
- 2-4 pros
- 1-3 cons
- warnings if any risk (very light semesters delaying graduation, retakes too late, etc.)
Pick bestPlanIndex as the index of the best plan.

DATA:
{JsonSerializer.Serialize(compact)}
""";

            // ✅ Responses API uses text.format for output format config
            // (not response_format)
            var body = new
            {
                model,
                instructions = systemInstructions,
                input = userInput,
                temperature = 0.2,
                text = new
                {
                    format = new
                    {
                        type = "json_schema",
                        name = "course_plan_ai_insights",
                        schema,
                        strict = true
                    }
                }
            };

            using var req = new HttpRequestMessage(HttpMethod.Post, "https://api.openai.com/v1/responses");
            req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
            req.Content = new StringContent(JsonSerializer.Serialize(body), Encoding.UTF8, "application/json");

            using var res = await _http.SendAsync(req, ct);
            var raw = await res.Content.ReadAsStringAsync(ct);

            if (!res.IsSuccessStatusCode)
            {
                _logger.LogError("OpenAI Responses error {Status}: {Body}", (int)res.StatusCode, raw);
                throw new InvalidOperationException($"OpenAI error {(int)res.StatusCode}: {raw}");
            }

            var jsonText = ExtractFirstOutputText(raw);

            var parsed = JsonSerializer.Deserialize<CoursePlanAiInsightsDto>(
                jsonText,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
            );

            if (parsed == null)
                throw new InvalidOperationException("Failed to parse AI JSON output.");

            // Safety clamp
            if (parsed.BestPlanIndex < 0 || parsed.BestPlanIndex >= plans.Count)
                parsed.BestPlanIndex = 0;

            // Ensure we have an insight for each plan (fallback fill)
            var byIndex = parsed.PlanInsights.ToDictionary(x => x.PlanIndex, x => x);
            parsed.PlanInsights = Enumerable.Range(0, plans.Count)
                .Select(i => byIndex.TryGetValue(i, out var v)
                    ? v
                    : new CoursePlanAiPlanInsightDto
                    {
                        PlanIndex = i,
                        Score = 50,
                        Explanation = $"Strategy: {plans[i].Strategy}.",
                        Pros = new(),
                        Cons = new(),
                        Warnings = new()
                    })
                .ToList();

            return parsed;
        }

        private static string ExtractFirstOutputText(string raw)
        {
            using var doc = JsonDocument.Parse(raw);

            if (!doc.RootElement.TryGetProperty("output", out var output) ||
                output.ValueKind != JsonValueKind.Array)
                throw new InvalidOperationException("Unexpected Responses API response: missing output[]");

            foreach (var item in output.EnumerateArray())
            {
                if (!item.TryGetProperty("content", out var content) ||
                    content.ValueKind != JsonValueKind.Array)
                    continue;

                foreach (var c in content.EnumerateArray())
                {
                    if (c.TryGetProperty("type", out var type) &&
                        type.ValueKind == JsonValueKind.String &&
                        type.GetString() == "output_text" &&
                        c.TryGetProperty("text", out var text) &&
                        text.ValueKind == JsonValueKind.String)
                    {
                        var s = text.GetString();
                        if (!string.IsNullOrWhiteSpace(s)) return s!;
                    }
                }
            }

            throw new InvalidOperationException("No output_text found in Responses API response.");
        }
    }
}