// <auto-generated />
using System;
using EduAdvisory_Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace EduAdvisory_Backend.Migrations
{
    [DbContext(typeof(EduAdvisoryDbContext))]
    [Migration("20260602183204_AiAssistant")]
    partial class AiAssistant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduAdvisory_Backend.Models.Advisor", b =>
                {
                    b.Property<int>("AdvisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("advisor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdvisorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("office");

                    b.Property<string>("OfficeHours")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("office_hours");

                    b.HasKey("AdvisorId")
                        .HasName("advisor_pkey");

                    b.HasIndex(new[] { "Email" }, "advisor_email_key")
                        .IsUnique();

                    b.ToTable("advisor");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AdvisorAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("availability_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvailabilityId"));

                    b.Property<int>("AdvisorId")
                        .HasColumnType("integer")
                        .HasColumnName("advisor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_booked");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("AdvisorId");

                    b.ToTable("advisor_availability");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AdvisorAvailabilityRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RuleId"));

                    b.Property<int>("AdvisorId")
                        .HasColumnType("integer")
                        .HasColumnName("advisor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("RuleId");

                    b.HasIndex("AdvisorId");

                    b.ToTable("advisor_availability_rule");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AiChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.HasKey("MessageId")
                        .HasName("ai_chat_messages_pkey");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_ai_chat_messages_session_id");

                    b.ToTable("ai_chat_messages");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AiChatSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("SessionId")
                        .HasName("ai_chat_sessions_pkey");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("idx_ai_chat_sessions_student_id");

                    b.ToTable("ai_chat_sessions");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AiDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("course_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Semester")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("semester");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("DocumentId")
                        .HasName("ai_documents_pkey");

                    b.HasIndex("CourseCode", "DocumentType")
                        .HasDatabaseName("idx_ai_documents_course_type");

                    b.ToTable("ai_documents");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AiDocumentChunk", b =>
                {
                    b.Property<int>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("chunk_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChunkId"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk_text");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("course_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<string>("SectionTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("section_title");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("ChunkId")
                        .HasName("ai_document_chunks_pkey");

                    b.HasIndex("CourseCode")
                        .HasDatabaseName("idx_ai_chunks_course_code");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("idx_ai_chunks_document_type");

                    b.ToTable("ai_document_chunks");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AiRetrievalLog", b =>
                {
                    b.Property<int>("RetrievalLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("retrieval_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RetrievalLogId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PluginUsed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plugin_used");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("ResponseSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("response_source");

                    b.Property<string>("RetrievedChunkIds")
                        .HasColumnType("text")
                        .HasColumnName("retrieved_chunk_ids");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<double?>("TopSimilarityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("top_similarity_score");

                    b.HasKey("RetrievalLogId")
                        .HasName("ai_retrieval_logs_pkey");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("idx_ai_retrieval_logs_student_id");

                    b.ToTable("ai_retrieval_logs");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("announcement_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnouncementId"));

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("integer")
                        .HasColumnName("advisor_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("AnnouncementId")
                        .HasName("announcement_pkey");

                    b.HasIndex("AdvisorId");

                    b.ToTable("announcement");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AppGoogleAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GoogleEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("google_email");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("TokenExpiryUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expiry_utc");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("app_google_account");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.BroadcastAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attachment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttachmentId"));

                    b.Property<int>("BroadcastMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("broadcast_message_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AttachmentId")
                        .HasName("broadcast_attachment_pkey");

                    b.HasIndex("BroadcastMessageId");

                    b.ToTable("broadcast_attachment");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.BroadcastMessage", b =>
                {
                    b.Property<int>("BroadcastMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("broadcast_message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BroadcastMessageId"));

                    b.Property<int>("AdvisorId")
                        .HasColumnType("integer")
                        .HasColumnName("advisor_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("BroadcastMessageId")
                        .HasName("broadcast_message_pkey");

                    b.HasIndex("AdvisorId");

                    b.ToTable("broadcast_message");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.BroadcastRecipient", b =>
                {
                    b.Property<int>("BroadcastRecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("broadcast_recipient_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BroadcastRecipientId"));

                    b.Property<int>("BroadcastMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("broadcast_message_id");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("BroadcastRecipientId")
                        .HasName("broadcast_recipient_pkey");

                    b.HasIndex("StudentId");

                    b.HasIndex("BroadcastMessageId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("broadcast_recipient_message_student_unique");

                    b.ToTable("broadcast_recipient");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MessageId")
                        .HasName("chat_message_pkey");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("chat_message");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.ChatbotHistory", b =>
                {
                    b.Property<int>("ChatbotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("chatbot_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatbotId"));

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<string>("Question")
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ChatbotId")
                        .HasName("chatbot_history_pkey");

                    b.HasIndex("StudentId");

                    b.ToTable("chatbot_history");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("conversation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversationId"));

                    b.Property<int>("AdvisorId")
                        .HasColumnType("integer")
                        .HasColumnName("advisor_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("ConversationId")
                        .HasName("conversation_pkey");

                    b.HasIndex("StudentId");

                    b.HasIndex("AdvisorId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("conversation_advisor_student_unique");

                    b.ToTable("conversation");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.CourseGradingSchema", b =>
                {
                    b.Property<int>("GradingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grading_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GradingId"));

                    b.Property<string>("ComponentName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("component_name");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<int?>("WeightPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("weight_percentage");

                    b.HasKey("GradingId")
                        .HasName("course_grading_schema_pkey");

                    b.HasIndex("CourseCode");

                    b.ToTable("course_grading_schema");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.CoursePrerequisite", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<string>("PrerequisiteCourseCode")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prerequisite_course_code");

                    b.HasKey("CourseCode", "PrerequisiteCourseCode");

                    b.HasIndex("PrerequisiteCourseCode");

                    b.ToTable("course_prerequisite");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.GeneratedStudyPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<string>("CourseCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<DateOnly?>("GenerationDate")
                        .HasColumnType("date")
                        .HasColumnName("generation_date");

                    b.Property<int?>("PlannedSemester")
                        .HasColumnType("integer")
                        .HasColumnName("planned_semester");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("PlanId")
                        .HasName("generated_study_plan_pkey");

                    b.HasIndex("CourseCode");

                    b.HasIndex("StudentId");

                    b.ToTable("generated_study_plan");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("meeting_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeetingId"));

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("integer")
                        .HasColumnName("advisor_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("GoogleSpaceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_space_name");

                    b.Property<DateTimeOffset?>("MeetingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meeting_date");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meeting_link");

                    b.Property<string>("MeetingType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meeting_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MeetingId")
                        .HasName("meeting_pkey");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("StudentId");

                    b.ToTable("meeting");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.MessageAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attachment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AttachmentId")
                        .HasName("message_attachment_pkey");

                    b.HasIndex("MessageId");

                    b.ToTable("message_attachment");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.RiskInterventionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("integer")
                        .HasColumnName("advisor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("StudentId");

                    b.ToTable("risk_intervention_log");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisCourse", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("course_name");

                    b.Property<int>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.HasKey("CourseCode")
                        .HasName("sis_course_pkey");

                    b.ToTable("sis_course");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisCourseAssessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assessment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssessmentId"));

                    b.Property<int?>("AbsencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("absences_count");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<int?>("CourseCredits")
                        .HasColumnType("integer")
                        .HasColumnName("course_credits");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("MaxAbsences")
                        .HasColumnType("integer")
                        .HasColumnName("max_absences");

                    b.Property<DateOnly?>("SemesterEndDate")
                        .HasColumnType("date")
                        .HasColumnName("semester_end_date");

                    b.Property<DateOnly?>("SemesterStartDate")
                        .HasColumnType("date")
                        .HasColumnName("semester_start_date");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("AssessmentId")
                        .HasName("sis_course_assessment_pkey");

                    b.HasIndex("CourseCode");

                    b.HasIndex("StudentId");

                    b.ToTable("sis_course_assessment");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisCurrentEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnrollmentId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<string>("Semester")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("semester");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("EnrollmentId")
                        .HasName("sis_current_enrollment_pkey");

                    b.HasIndex("CourseCode");

                    b.HasIndex("StudentId");

                    b.ToTable("sis_current_enrollment");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisStudent", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("AcademicStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("academic_status");

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("integer")
                        .HasColumnName("advisor_id");

                    b.Property<decimal?>("CurrentGpa")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("current_gpa");

                    b.Property<int?>("CurrentSemester")
                        .HasColumnType("integer")
                        .HasColumnName("current_semester");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("ProgramCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("program_code");

                    b.HasKey("StudentId")
                        .HasName("sis_student_pkey");

                    b.HasIndex("AdvisorId");

                    b.ToTable("sis_student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisStudentCourseHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<decimal?>("FinalGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("final_grade");

                    b.Property<string>("Semester")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("semester");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("HistoryId")
                        .HasName("sis_student_course_history_pkey");

                    b.HasIndex("CourseCode");

                    b.HasIndex("StudentId");

                    b.ToTable("sis_student_course_history");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisStudentGrade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grade_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GradeId"));

                    b.Property<string>("ComponentName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("component_name");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("grade");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("GradeId")
                        .HasName("sis_student_grades_pkey");

                    b.HasIndex("CourseCode");

                    b.HasIndex("StudentId");

                    b.ToTable("sis_student_grades");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.StudentRisk", b =>
                {
                    b.Property<int>("RiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("risk_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RiskId"));

                    b.Property<DateTime?>("CalculatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("calculated_at");

                    b.Property<string>("CourseCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<decimal?>("RiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("risk_score");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("RiskId")
                        .HasName("student_risk_pkey");

                    b.HasIndex("CourseCode");

                    b.HasIndex("StudentId");

                    b.ToTable("student_risk");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.StudyGuide", b =>
                {
                    b.Property<int>("StudyGuideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("study_guide_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudyGuideId"));

                    b.Property<string>("CourseCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("course_code");

                    b.Property<string>("ProgramCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("program_code");

                    b.Property<int?>("RecommendedSemester")
                        .HasColumnType("integer")
                        .HasColumnName("recommended_semester");

                    b.HasKey("StudyGuideId")
                        .HasName("study_guide_pkey");

                    b.HasIndex("CourseCode");

                    b.ToTable("study_guide");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeycloakId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("keycloak_id");

                    b.Property<int?>("LinkedAdvisorId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_advisor_id");

                    b.Property<int?>("LinkedStudentId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_student_id");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("LinkedAdvisorId");

                    b.HasIndex("LinkedStudentId");

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("MeetingRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<int>("AdvisorId")
                        .HasColumnType("integer")
                        .HasColumnName("advisor_id");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("RequestId");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("StudentId");

                    b.ToTable("meeting_request");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AdvisorAvailability", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Advisor", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AdvisorAvailabilityRule", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Advisor", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AiChatMessage", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.AiChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AiDocumentChunk", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.AiDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.Announcement", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Advisor", "Advisor")
                        .WithMany("Announcements")
                        .HasForeignKey("AdvisorId")
                        .HasConstraintName("announcement_advisor_id_fkey");

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.BroadcastAttachment", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.BroadcastMessage", "BroadcastMessage")
                        .WithMany("Attachments")
                        .HasForeignKey("BroadcastMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("broadcast_attachment_message_id_fkey");

                    b.Navigation("BroadcastMessage");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.BroadcastMessage", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Advisor", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("broadcast_message_advisor_id_fkey");

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.BroadcastRecipient", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.BroadcastMessage", "BroadcastMessage")
                        .WithMany("Recipients")
                        .HasForeignKey("BroadcastMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("broadcast_recipient_broadcast_message_id_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("broadcast_recipient_student_id_fkey");

                    b.Navigation("BroadcastMessage");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.ChatMessage", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chat_message_conversation_id_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("chat_message_sender_user_id_fkey");

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.ChatbotHistory", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany("ChatbotHistories")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("chatbot_history_student_id_fkey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.Conversation", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Advisor", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("conversation_advisor_id_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("conversation_student_id_fkey");

                    b.Navigation("Advisor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.CourseGradingSchema", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.SisCourse", "CourseCodeNavigation")
                        .WithMany("CourseGradingSchemas")
                        .HasForeignKey("CourseCode")
                        .IsRequired()
                        .HasConstraintName("course_grading_schema_course_code_fkey");

                    b.Navigation("CourseCodeNavigation");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.CoursePrerequisite", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.SisCourse", "Course")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduAdvisory_Backend.Models.SisCourse", "PrerequisiteCourse")
                        .WithMany("RequiredBy")
                        .HasForeignKey("PrerequisiteCourseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PrerequisiteCourse");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.GeneratedStudyPlan", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.SisCourse", "CourseCodeNavigation")
                        .WithMany("GeneratedStudyPlans")
                        .HasForeignKey("CourseCode")
                        .HasConstraintName("generated_study_plan_course_code_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany("GeneratedStudyPlans")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("generated_study_plan_student_id_fkey");

                    b.Navigation("CourseCodeNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.Meeting", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Advisor", "Advisor")
                        .WithMany("Meetings")
                        .HasForeignKey("AdvisorId")
                        .HasConstraintName("meeting_advisor_id_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany("Meetings")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("meeting_student_id_fkey");

                    b.Navigation("Advisor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.MessageAttachment", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.ChatMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_attachment_message_id_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.RiskInterventionLog", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Advisor", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisCourseAssessment", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.SisCourse", "CourseCodeNavigation")
                        .WithMany("SisCourseAssessments")
                        .HasForeignKey("CourseCode")
                        .IsRequired()
                        .HasConstraintName("sis_course_assessment_course_code_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany("SisCourseAssessments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("sis_course_assessment_student_id_fkey");

                    b.Navigation("CourseCodeNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisCurrentEnrollment", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.SisCourse", "CourseCodeNavigation")
                        .WithMany("SisCurrentEnrollments")
                        .HasForeignKey("CourseCode")
                        .IsRequired()
                        .HasConstraintName("sis_current_enrollment_course_code_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany("SisCurrentEnrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("sis_current_enrollment_student_id_fkey");

                    b.Navigation("CourseCodeNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisStudent", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Advisor", "Advisor")
                        .WithMany("SisStudents")
                        .HasForeignKey("AdvisorId")
                        .HasConstraintName("sis_student_advisor_id_fkey");

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisStudentCourseHistory", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.SisCourse", "CourseCodeNavigation")
                        .WithMany("SisStudentCourseHistories")
                        .HasForeignKey("CourseCode")
                        .IsRequired()
                        .HasConstraintName("sis_student_course_history_course_code_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany("SisStudentCourseHistories")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("sis_student_course_history_student_id_fkey");

                    b.Navigation("CourseCodeNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisStudentGrade", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.SisCourse", "CourseCodeNavigation")
                        .WithMany("SisStudentGrades")
                        .HasForeignKey("CourseCode")
                        .IsRequired()
                        .HasConstraintName("sis_student_grades_course_code_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany("SisStudentGrades")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("sis_student_grades_student_id_fkey");

                    b.Navigation("CourseCodeNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.StudentRisk", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.SisCourse", "CourseCodeNavigation")
                        .WithMany("StudentRisks")
                        .HasForeignKey("CourseCode")
                        .HasConstraintName("student_risk_course_code_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany("StudentRisks")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("student_risk_student_id_fkey");

                    b.Navigation("CourseCodeNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.StudyGuide", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.SisCourse", "CourseCodeNavigation")
                        .WithMany("StudyGuides")
                        .HasForeignKey("CourseCode")
                        .HasConstraintName("study_guide_course_code_fkey");

                    b.Navigation("CourseCodeNavigation");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.User", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Advisor", "LinkedAdvisor")
                        .WithMany("Users")
                        .HasForeignKey("LinkedAdvisorId")
                        .HasConstraintName("users_linked_advisor_id_fkey");

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "LinkedStudent")
                        .WithMany("Users")
                        .HasForeignKey("LinkedStudentId")
                        .HasConstraintName("users_linked_student_id_fkey");

                    b.Navigation("LinkedAdvisor");

                    b.Navigation("LinkedStudent");
                });

            modelBuilder.Entity("MeetingRequest", b =>
                {
                    b.HasOne("EduAdvisory_Backend.Models.Advisor", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduAdvisory_Backend.Models.SisStudent", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.Advisor", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Meetings");

                    b.Navigation("SisStudents");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AiChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.AiDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.BroadcastMessage", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.ChatMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisCourse", b =>
                {
                    b.Navigation("CourseGradingSchemas");

                    b.Navigation("GeneratedStudyPlans");

                    b.Navigation("Prerequisites");

                    b.Navigation("RequiredBy");

                    b.Navigation("SisCourseAssessments");

                    b.Navigation("SisCurrentEnrollments");

                    b.Navigation("SisStudentCourseHistories");

                    b.Navigation("SisStudentGrades");

                    b.Navigation("StudentRisks");

                    b.Navigation("StudyGuides");
                });

            modelBuilder.Entity("EduAdvisory_Backend.Models.SisStudent", b =>
                {
                    b.Navigation("ChatbotHistories");

                    b.Navigation("GeneratedStudyPlans");

                    b.Navigation("Meetings");

                    b.Navigation("SisCourseAssessments");

                    b.Navigation("SisCurrentEnrollments");

                    b.Navigation("SisStudentCourseHistories");

                    b.Navigation("SisStudentGrades");

                    b.Navigation("StudentRisks");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
